FROM ubuntu:latest

RUN apt-get update  \
    && apt-get upgrade -y \
    && apt-get install -y git make build-essential pkg-config rtl-sdr librtlsdr-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN git clone https://github.com/toughIQ/dump1090.git 
WORKDIR /dump1090

RUN make

CMD ["./dump1090", "--net"]


