FROM registry.fedoraproject.org/fedora-minimal:38

RUN microdnf install -y git make @development-tools rtl-sdr-devel && microdnf clean all

RUN git clone https://github.com/toughIQ/dump1090.git 
WORKDIR /dump1090

RUN make


